name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          submodules: true

      - name: Publish Website
        uses: chabad360/hugo-gh-pages@v2
        with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
          cname: lemonedia.se